# Generated by Django 6.0.1 on 2026-01-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('DAR', 'Dar es Salaam'), ('ARU', 'Arusha'), ('ZAN', 'Zanzibar'), ('ALL', 'All Tanzania')], max_length=3)),
                ('category', models.CharField(choices=[('nature', '🌿 Nature & Wildlife'), ('beach', '🏖️ Beach & Coast'), ('culture', '🎭 Culture & History'), ('adventure', '🗻 Adventure & Sports'), ('food', '🍲 Food & Dining'), ('shopping', '🛍️ Shopping & Markets')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=100)),
                ('best_time_to_visit', models.CharField(default='Morning', max_length=100)),
                ('estimated_visit_time', models.CharField(default='2-3 hours', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Use Unsplash or other image URLs')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourism.touristattraction')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(default='1 day', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.TextField(help_text="List what's included, separated by commas")),
                ('excludes', models.TextField(blank=True, help_text="List what's excluded, separated by commas")),
                ('is_featured', models.BooleanField(default=False)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='tourism.touristattraction')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.touristattraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
