# Generated by Django 6.0.1 on 2026-02-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_touristattraction_partner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
