# Generated by Django 6.0.1 on 2026-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('DAR', 'Dar es Salaam'), ('ARU', 'Arusha'), ('ZAN', 'Zanzibar')], max_length=3, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(help_text='Short catchy phrase about the city', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the city')),
                ('history', models.TextField(blank=True, help_text='Brief history of the city')),
                ('culture', models.TextField(blank=True, help_text='Cultural information')),
                ('hero_image', models.URLField(help_text='Main hero image URL')),
                ('gallery_images', models.JSONField(default=list, help_text='List of gallery image URLs')),
                ('population', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='Swahili, English', max_length=100)),
                ('currency', models.CharField(default='Tanzanian Shilling (TZS)', max_length=50)),
                ('timezone', models.CharField(default='EAT (UTC+3)', max_length=50)),
                ('stadium_name', models.CharField(max_length=200)),
                ('stadium_capacity', models.IntegerField()),
                ('stadium_image', models.URLField(blank=True)),
                ('matches_count', models.IntegerField(default=0, help_text='Number of AFCON matches hosted')),
                ('best_time_to_visit', models.CharField(help_text='Best months to visit', max_length=200)),
                ('average_temperature', models.CharField(help_text='Average temperature during AFCON', max_length=100)),
                ('weather_info', models.TextField(blank=True)),
                ('how_to_get_there', models.TextField(help_text='How to reach the city')),
                ('getting_around', models.TextField(help_text='Local transportation options')),
                ('airport_info', models.TextField(blank=True)),
                ('famous_for', models.TextField(help_text='What the city is famous for')),
                ('local_cuisine', models.TextField(help_text='Famous local dishes')),
                ('popular_activities', models.JSONField(default=list, help_text='List of popular activities')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
    ]
