import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'afcon.settings')
django.setup()

from hotels.models import Hotel

# Real hotels in Tanzania with actual images
hotels_data = [
    {
        'name': 'Serena Hotel Dar es Salaam',
        'city': 'DAR',
        'address': 'Ohio Street, Dar es Salaam, Tanzania',
        'description': 'Luxury 5-star hotel with sea views, swimming pools, and multiple dining options. Perfect for AFCON visitors.',
        'stars': 5,
        'price_per_night': 350,
        'available_rooms': 25,
        'image_url': 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'Hyatt Regency Dar es Salaam',
        'city': 'DAR',
        'address': 'Kivukoni Front, Dar es Salaam',
        'description': 'Modern hotel with harbor views, spa, and direct access to business district. Close to National Stadium.',
        'stars': 5,
        'price_per_night': 320,
        'available_rooms': 30,
        'image_url': 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'Kilimanjaro Hotel Arusha',
        'city': 'ARU',
        'address': 'Sokoine Road, Arusha, Tanzania',
        'description': 'Historic hotel with views of Mount Meru. Perfect base for safari adventures before/after AFCON matches.',
        'stars': 4,
        'price_per_night': 220,
        'available_rooms': 18,
        'image_url': 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': False,
        'parking': True,
    },
    {
        'name': 'Arusha Serena Hotel',
        'city': 'ARU',
        'address': 'Dodoma Road, Arusha',
        'description': 'Luxury resort-style hotel with tropical gardens and pool. Offers safari packages for AFCON visitors.',
        'stars': 5,
        'price_per_night': 280,
        'available_rooms': 20,
        'image_url': 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'Zanzibar Serena Hotel',
        'city': 'ZAN',
        'address': 'Shangani Street, Stone Town, Zanzibar',
        'description': 'Beachfront hotel in historic Stone Town. Combines Arabian architecture with modern amenities.',
        'stars': 5,
        'price_per_night': 400,
        'available_rooms': 15,
        'image_url': 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'The Residence Zanzibar',
        'city': 'ZAN',
        'address': 'Kiwengwa, Zanzibar',
        'description': 'Luxury villa resort with private pool villas. Perfect for post-AFCON relaxation on the beach.',
        'stars': 5,
        'price_per_night': 550,
        'available_rooms': 12,
        'image_url': 'https://images.unsplash.com/photo-1561501878-aabd62634533?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'Holiday Inn Dar es Salaam',
        'city': 'DAR',
        'address': 'P.O. Box 801, Dar es Salaam',
        'description': 'Modern business hotel with conference facilities. Great for football teams and delegations.',
        'stars': 4,
        'price_per_night': 180,
        'available_rooms': 35,
        'image_url': 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': True,
        'parking': True,
    },
    {
        'name': 'Mount Meru Hotel Arusha',
        'city': 'ARU',
        'address': 'Old Moshi Road, Arusha',
        'description': 'Comfortable hotel with mountain views. Popular with safari tour groups.',
        'stars': 3,
        'price_per_night': 120,
        'available_rooms': 40,
        'image_url': 'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': False,
        'restaurant': True,
        'gym': False,
        'parking': True,
    },
    {
        'name': 'Tembo Hotel Zanzibar',
        'city': 'ZAN',
        'address': 'Shangani, Stone Town, Zanzibar',
        'description': 'Historic hotel with ocean views. Walking distance to local markets and restaurants.',
        'stars': 4,
        'price_per_night': 190,
        'available_rooms': 28,
        'image_url': 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
        'wifi': True,
        'pool': True,
        'restaurant': True,
        'gym': False,
        'parking': True,
    },
]

print("Creating hotels with real images...")
for hotel_data in hotels_data:
    hotel, created = Hotel.objects.update_or_create(
        name=hotel_data['name'],
        defaults=hotel_data
    )
    print(f"{'✅ Created' if created else '📝 Updated'}: {hotel.name}")

print(f"\n🎉 Total hotels in database: {Hotel.objects.count()}")