# Generated by Django 6.0.1 on 2026-04-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_images/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='Or provide external image URL', null=True)),
                ('image_type', models.CharField(choices=[('logo', 'Business Logo'), ('cover', 'Cover Photo'), ('interior', 'Interior / Facility'), ('product', 'Product / Service'), ('team', 'Team Photo'), ('event', 'Event / Activity'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partners.partner')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
