# Generated by Django 6.0.1 on 2026-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='delivery_radius_km',
            field=models.IntegerField(default=5, help_text='Maximum delivery radius in kilometers'),
        ),
        migrations.AddField(
            model_name='partner',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., -6.7924 for Dar es Salaam)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 39.2083 for Dar es Salaam)', max_digits=10, null=True),
        ),
    ]
