# Generated by Django 6.0.1 on 2026-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='last_hotel_query',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='last_tour_query',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='travel_budget',
            field=models.CharField(choices=[('budget', '💰 Budget (< $100/night)'), ('midrange', '💵 Mid-range ($100-$300/night)'), ('luxury', '💎 Luxury ($300+/night)')], default='midrange', max_length=20),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='travel_group',
            field=models.CharField(choices=[('solo', '👤 Solo Traveler'), ('couple', '👫 Couple'), ('family', '👨\u200d👩\u200d👧\u200d👦 Family'), ('friends', '👥 Friends'), ('business', '💼 Business')], default='solo', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='intent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatprofile',
            name='interests',
            field=models.CharField(choices=[('football', '⚽ Football'), ('safari', '🦁 Safari & Wildlife'), ('beach', '🏖️ Beach & Relaxation'), ('culture', '🎭 Culture & History'), ('adventure', '🗻 Adventure & Hiking'), ('food', '🍲 Food & Dining'), ('shopping', '🛍️ Shopping'), ('luxury', '🌟 Luxury Travel')], default='football', max_length=50),
        ),
    ]
