# Generated by Django 6.0.1 on 2026-02-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatsession_options_chatmessage_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatprofile',
            old_name='updated_at',
            new_name='last_active',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
