# Generated by Django 6.0.1 on 2026-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_newscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchnews',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='goal',
            name='celebration_image_url',
            field=models.URLField(blank=True, help_text='URL for goal celebration image', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='highlight_thumbnail_url',
            field=models.URLField(blank=True, help_text='URL for highlight video thumbnail', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='lineup_image_url',
            field=models.URLField(blank=True, help_text='URL for team lineup image', null=True),
        ),
        migrations.AddField(
            model_name='matchnews',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL for video thumbnail', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='celebration_photo_url',
            field=models.URLField(blank=True, help_text='URL for goal celebration photo', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='club_logo_url',
            field=models.URLField(blank=True, help_text='URL for club logo', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_photo_url',
            field=models.URLField(blank=True, help_text='URL for player jersey photo', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='training_photo_url',
            field=models.URLField(blank=True, help_text='URL for training session photo', null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='night_image_url',
            field=models.URLField(blank=True, help_text='URL for night view of stadium', null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='pitch_image_url',
            field=models.URLField(blank=True, help_text='URL for pitch/field image', null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='stands_image_url',
            field=models.URLField(blank=True, help_text='URL for stands/seats image', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_photo_url',
            field=models.URLField(blank=True, help_text='URL for coach photo', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_photo_url',
            field=models.URLField(blank=True, help_text="URL for team's home stadium photo", null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_photo_url',
            field=models.URLField(blank=True, help_text='URL for team group photo', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL for match poster/cover image', null=True),
        ),
        migrations.AlterField(
            model_name='matchnews',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of gallery image URLs'),
        ),
        migrations.AlterField(
            model_name='matchnews',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for video content'),
        ),
        migrations.AlterField(
            model_name='player',
            name='action_photo_url',
            field=models.URLField(blank=True, help_text='URL for action photo during match', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL for player portrait photo', null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for gallery'),
        ),
    ]
