# Generated by Django 6.0.1 on 2026-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_booking_updated_at_remove_hotel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(default='Standard Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
