# Generated by Django 6.0.1 on 2026-01-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_booking_created_at_remove_booking_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
