# Generated by Django 6.0.1 on 2026-01-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='afcon_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
